services:
  db:
    image: postgres:latest
    container_name: kurierdb
    restart: always
    env_file:
      - database/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kurier-network

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile

    networks:
    - kurier-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - kurier-network
volumes:
  postgres_data:
networks:
  kurier-network:
    driver: bridge